config/routes.rb
Rails.application.routes.draw do
  root 'poker_hands#new'
  resources :poker_hands
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/poker_hand.rb
class PokerHand < ApplicationRecord
  # given more time I would have used drop down menus for the cards in the form
  VALID_CARDS = %w[
    AD 2D 3D 4D 5D 6D 7D 8D 9D 10D JD KD QD AD
    AC 2C 3C 4C 5C 6C 7C 8C 9C 10C JC KC QC AC
    AH 2H 3H 4H 5H 6H 7H 8H 9H 10H JH KH QH AH
    AS 2S 3S 4S 5S 6S 7S 8S 9S 10S JS KS QS AS
  ].freeze

  validates_each :cards do |record, attr, value|
    if value.reject(&:blank?).size != 5
      record.errors.add(attr,
                        'Error: Hand size should be 5. Please input 5 valid cards')
    end
    value.all?(&:present?) && value.each do |card|
      record.errors.add(attr, "Error: #{card} is not a valid card.") unless VALID_CARDS.include?(card)
    end
    value.all?(&:present?) && record.errors.add(attr, 'Error: No duplicate cards') if value.uniq.size != value.size
  end

  def rank
    if wildcard.present?
      Rank.new(cards: cards.map { |card| Card.new(card) }, wildcard: Card.new(wildcard)).call
    else
      Rank.new(cards: cards.map { |card| Card.new(card) }).call
    end
  end

  def self.cache(id, value = nil)
    hand = Rails.cache.read("hand:#{id}") || []

    Rails.cache.write("hand:#{id}", hand << value) if value

    new(
      cards: hand
    )
  end

  def self.clear_cache(id)
    Rails.cache.delete("hand:#{id}")
    Rails.cache.delete("step:#{id}")

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Getting a CSRF error. I can't spend more time debugging the error
	# so I'm just disabling it for now.
	protect_from_forgery with: :null_session
end

app/controllers/poker_hands_controller.rb
class PokerHandsController < ApplicationController
  before_action :set_poker_hand, only: %i[show edit update destroy]

  # GET /poker_hands or /poker_hands.json
  def index
    @poker_hands = PokerHand.all
  end

  # GET /poker_hands/1 or /poker_hands/1.json
  def show; end

  # GET /poker_hands/new
  def new
    # Fill from cache
    @poker_hand ||= PokerHand.cache(session.id)

    # Set up step
    @step ||= Rails.cache.fetch("step:#{session.id}") { :first_card }
  end

  # GET /poker_hands/1/edit
  def edit; end

  # POST /poker_hands or /poker_hands.json
  def create
    @poker_hand = PokerHand.new(poker_hand_params)

    respond_to do |format|
      if @poker_hand.save
        format.html { redirect_to poker_hand_url(@poker_hand), notice: @poker_hand.rank }
        format.json { render :show, status: :created, location: @poker_hand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @poker_hand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poker_hands/1 or /poker_hands/1.json
  def update
    respond_to do |format|
      if @poker_hand.update(poker_hand_params)
        format.html { redirect_to poker_hand_url(@poker_hand), notice: 'Poker hand was successfully updated.' }
        format.json { render :show, status: :ok, location: @poker_hand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @poker_hand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poker_hands/1 or /poker_hands/1.json
  def destroy
    @poker_hand.destroy

    respond_to do |format|
      format.html { redirect_to poker_hands_url, notice: 'Poker hand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_poker_hand
    @poker_hand = PokerHand.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def poker_hand_params
    params.require(:poker_hand).permit(:wildcard, cards: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poker_hands_helper.rb
module PokerHandsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BTSTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/poker_hands/_form.html.erb
<%= form_with(model: @poker_hand, class: "contents", data: {controller: 'hand' } ) do |form| %>
  <% if poker_hand.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(poker_hand.errors.count, "error") %> prohibited this poker_hand from being saved:</h2>

      <ul>
        <% poker_hand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= @poker_hand.cards %>


  <% if @step == :first_card %>
	  <p>Add your first card</p>
	  <%= form.text_field :card_1, data: {target: 'hand.card1'} %>
	    <button data-action='click->hand#next'>Next</button>
  <% end %>

   <% if @step == :second_card %>
	  <p>Add your second card</p>
	  <%= form.text_field :card_2, data: {target: 'hand.card2'} %>
	    <button data-action='click->hand#next'>Next</button>
      <button data-action="click->hand#previous">Previous</button>
  <% end %>

  <% if @step == :third_card %>
    <p>Add your third card</p>
    <%= form.text_field :card_3, data: {target: 'hand.card3'} %>
      <button data-action='click->hand#next'>Next</button>
      <button data-action="click->hand#previous">Previous</button>
  <% end %>

  <% if @step == :fourth_card %>
    <p>Add your fourth card</p>
    <%= form.text_field :card_4, data: {target: 'hand.card4'} %>
      <button data-action='click->hand#next'>Next</button>
      <button data-action="click->hand#previous">Previous</button>
  <% end %>

    <% if @step == :fifth_card %>
	<p>Add your fifth card</p>
	<%= form.text_field :card_5, data: {target: 'hand.card5'} %>
	<button data-action='click->hand#next'>Next</button>
  <button data-action="click->hand#previous">Previous</button>
  <% end %>
<% end %>

<body data-controller="radiolabel"></body>

app/views/poker_hands/_form_wizard.html.erb
<div class="my-5">
		<%= f.text_field :card_1, data: {target: 'hand.card1'} %>
		<%= f.text_field :card_2, data: {target: 'hand.card2'} %>
		<%= f.text_field :card_3, data: {target: 'hand.card3'} %>
		<%= f.text_field :card_4, data: {target: 'hand.card4'} %>
		<%= f.text_field :card_5, data: {target: 'hand.card5'} %>
</div>

<button data-action='click->hand#next'>Next</button>

app/views/poker_hands/_poker_hand.html.erb
<div id="<%= dom_id poker_hand %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Cards:</strong>
    <%= poker_hand.cards %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this poker hand", poker_hand, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this poker hand', edit_poker_hand_path(poker_hand), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/poker_hands/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing poker hand</h1>

  <%= render "form", poker_hand: @poker_hand %>

  <%= link_to "Show this poker hand", @poker_hand, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to poker hands", poker_hands_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/poker_hands/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Poker hands</h1>
    <%= link_to 'New poker hand', new_poker_hand_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="poker_hands" class="min-w-full">
    <%= render @poker_hands %>
  </div>
</div>

app/views/poker_hands/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New poker hand</h1>

  <%= render "form", poker_hand: @poker_hand %>

  <%= link_to 'Back to poker hands', poker_hands_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/poker_hands/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @poker_hand %>

    <%= link_to 'Edit this poker_hand', edit_poker_hand_path(@poker_hand), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this poker_hand', poker_hand_path(@poker_hand), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to poker_hands', poker_hands_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>